#!/usr/bin/env python3
"""Replace cached_books.json with real post-1923 Turkish literary works.
Uses simple string construction to avoid encoding issues."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "cached_books.json"

C = {
    "Adana": (37.0000, 35.3213),
    "Adiyaman": (37.7648, 38.2786),
    "Afyonkarahisar": (38.7569, 30.5387),
    "Agri": (39.7191, 43.0503),
    "Amasya": (40.6499, 35.8353),
    "Ankara": (39.9334, 32.8597),
    "Antalya": (36.8841, 30.7056),
    "Artvin": (41.1828, 41.8183),
    "Aydin": (37.8560, 27.8416),
    "Balikesir": (39.6484, 27.8826),
    "Bilecik": (40.1553, 29.9833),
    "Bingol": (38.8847, 40.4982),
    "Bitlis": (38.3938, 42.1232),
    "Bolu": (40.7392, 31.6089),
    "Burdur": (37.7206, 30.2908),
    "Bursa": (40.1826, 29.0665),
    "Canakkale": (40.1553, 26.4142),
    "Cankiri": (40.6013, 33.6134),
    "Corum": (40.5506, 34.9556),
    "Denizli": (37.7765, 29.0864),
    "Diyarbakir": (37.9144, 40.2306),
    "Edirne": (41.6818, 26.5623),
    "Elazig": (38.6748, 39.2226),
    "Erzincan": (39.7500, 39.5000),
    "Erzurum": (39.9043, 41.2678),
    "Eskisehir": (39.7767, 30.5206),
    "Gaziantep": (37.0662, 37.3833),
    "Giresun": (40.9128, 38.3895),
    "Gumushane": (40.4602, 39.4814),
    "Hakkari": (37.5744, 43.7408),
    "Hatay": (36.4018, 36.3498),
    "Isparta": (37.7648, 30.5566),
    "Mersin": (36.8121, 34.6415),
    "Istanbul": (41.0082, 28.9784),
    "Izmir": (38.4237, 27.1428),
    "Kars": (40.6013, 43.0975),
    "Kastamonu": (41.3766, 33.7765),
    "Kayseri": (38.7312, 35.4787),
    "Kirklareli": (41.7370, 27.2242),
    "Kirsehir": (39.1425, 34.1709),
    "Kocaeli": (40.8533, 29.8815),
    "Konya": (37.8667, 32.4833),
    "Kutahya": (39.4167, 29.9833),
    "Malatya": (38.3552, 38.3095),
    "Manisa": (38.6191, 27.4289),
    "Kahramanmaras": (37.5858, 36.9371),
    "Mardin": (37.3212, 40.7245),
    "Mugla": (37.2153, 28.3636),
    "Mus": (38.9462, 41.7538),
    "Nevsehir": (38.6939, 34.6857),
    "Nigde": (37.9667, 34.6833),
    "Ordu": (40.9839, 37.8764),
    "Rize": (41.0201, 40.5234),
    "Sakarya": (40.7569, 30.3783),
    "Samsun": (41.2867, 36.3300),
    "Siirt": (37.9333, 41.9500),
    "Sinop": (42.0231, 35.1531),
    "Sivas": (39.7477, 37.0179),
    "Tekirdag": (40.9833, 27.5167),
    "Tokat": (40.3167, 36.5500),
    "Trabzon": (41.0015, 39.7178),
    "Tunceli": (39.3074, 39.4388),
    "Sanliurfa": (37.1591, 38.7969),
    "Usak": (38.6823, 29.4082),
    "Van": (38.4891, 43.4089),
    "Yozgat": (39.8181, 34.8148),
    "Zonguldak": (41.4564, 31.7987),
    "Aksaray": (38.3687, 34.0370),
    "Bayburt": (40.2552, 40.2249),
    "Karaman": (37.1810, 33.2158),
    "Kirsehir_71": (39.8468, 33.5153),
    "Batman": (37.8812, 41.1351),
    "Sirnak": (37.4187, 42.4918),
    "Bartin": (41.6344, 32.3375),
    "Ardahan": (41.1105, 42.7022),
    "Igdir": (39.9237, 44.0450),
    "Yalova": (40.6500, 29.2667),
    "Karabuk": (41.2061, 32.6204),
    "Kilis": (36.7184, 37.1212),
    "Osmaniye": (37.0742, 36.2478),
    "Duzce": (40.8380, 31.1610),
}

# (city_key, title, author, year, genre, loc, spatial, sentiment, quote, desc_tr, desc_en, ctx_tr, ctx_en)
DATA = [
    ("Adana", "Ince Memed", "Yasar Kemal", 1955, "Roman",
     "Cukurova, Adana", "Kirsal bolge", "Coskulu",
     "O yilani oldurene kadar daglarda tek basina dolasti.",
     "Cukurova'nin toprak agaligi duzenine baskaldiran Memed'in efsanelesen hikayesi.",
     "The epic tale of Memed, an outlaw who becomes a legend in the Cukurova plains.",
     "1950'ler Turkiye'sinde toprak reformu ve eskiyalik gelenegi.",
     "Land reform and banditry tradition in 1950s Turkey."),

    ("Adiyaman", "Soframiz Nur Hanemiz Mamur", "Sezai Karakoc", 1964, "Siir",
     "Kahta, Adiyaman", "Ilce", "Mistik",
     "Gunesin dogdugu yerde durur bir cocuk.",
     "Sezai Karakoc'un dogdugu topraklar olan Adiyaman/Kahta, Dirilis sairinin siirlerinde sikca yankilanir.",
     "The poet's birthplace Kahta echoes through his verses on spiritual rebirth.",
     "1960'lar Islami dusunce ve dirilis edebiyati akimi.",
     "1960s Islamic thought and the Dirilis (Resurrection) literary movement."),

    ("Afyonkarahisar", "Kocatepe'den Aksam", "Cahit Kulebi", 1967, "Siir",
     "Kocatepe, Afyonkarahisar", "Cografi bolge", "Vatansever",
     "Dag basini duman almis, Kocatepe yalnizdir.",
     "Kurtulus Savasi'nin donum noktasi olan Afyon'a ithafen yazilmis Cumhuriyet donemi siirleri.",
     "Republican-era poems dedicated to Afyon, the turning point of the War of Independence.",
     "Kurtulus Savasi ve Cumhuriyet'in ilk yillarindaki milli edebiyat ruhu.",
     "National literary spirit during the War of Independence and early Republic."),

    ("Agri", "Agridagi Efsanesi", "Yasar Kemal", 1970, "Roman",
     "Agri Dagi", "Cografi bolge", "Destansi",
     "Agridagi'nin basi dumanli, insanin yuregi umutlu.",
     "Agri Dagi cevresinde gecen bir ask ve isyan hikayesi; halk soylencelerinden beslenen destansi bir roman.",
     "An epic love and rebellion story set around Mount Ararat, drawing from folk legends.",
     "1970'ler Anadolu'sunda feodal yapi ve efsane anlaticiligi.",
     "Feudal structures and legend-telling in 1970s Anatolia."),

    ("Amasya", "Amasya'da Bir Gece", "Cemal Sureya", 1967, "Siir",
     "Merkez, Amasya", "Il merkezi", "Romantik",
     "Amasya'nin dar sokaklarinda bir aksamustu.",
     "Ikinci Yeni sairi Cemal Sureya'nin Amasya izlenimlerini yansitan siirsel kesit.",
     "A poetic cross-section reflecting the impressions of Amasya by Cemal Sureya.",
     "Ikinci Yeni siir akimi ve 1960'lar Turk siiri.",
     "The Ikinci Yeni (Second New) poetry movement of the 1960s."),

    ("Ankara", "Ankara", "Yakup Kadri Karaosmanoglu", 1934, "Roman",
     "Merkez, Ankara", "Baskent", "Elistirel",
     "Ankara; bir tasra kasabasindan baskente donusen ruh.",
     "Cumhuriyet'in ilk yillarinda Ankara'nin bir kasabadan baskente donusumunu uc kusak uzerinden anlatan roman.",
     "A novel depicting Ankara's transformation from a provincial town to a capital over three generations.",
     "Erken Cumhuriyet donemi ve Ankara'nin baskent olusu.",
     "Early Republican period and Ankara becoming the capital."),

    ("Antalya", "Mavi Surgun", "Halikarnas Balikcisi (Cevat Sakir Kabaagacli)", 1961, "Ani",
     "Bodrum/Mavi Yolculuk, Antalya", "Kiyi bolgesi", "Ozlem",
     "Denizin mavisi insanin icine isler.",
     "Halikarnas Balikcisi'nin Ege ve Akdeniz kiyilarindaki mavi yolculuk anilari ve deniz sevgisi.",
     "The Blue Voyage memoirs of the Fisherman of Halicarnassus along the Aegean and Mediterranean coasts.",
     "Akdeniz kulturu ve mavi yolculuk gelenegi.",
     "Mediterranean culture and the Blue Voyage tradition."),

    ("Artvin", "Artvin'in Daglari", "Kemalettin Kamu", 1945, "Siir",
     "Coruh Vadisi, Artvin", "Daglik bolge", "Huzunlu",
     "Artvin'in daglarina kar yagdi, yollar kapandi.",
     "Karadeniz'in yesil ve sisli daglarini anlatan Cumhuriyet donemi halk siiri tadindaki eser.",
     "A Republican-era poem in folk style describing the green misty mountains of the Black Sea.",
     "Cumhuriyet donemi halk siiri gelenegi.",
     "Republican-era folk poetry tradition."),

    ("Aydin", "Kuyucakli Yusuf", "Sabahattin Ali", 1937, "Roman",
     "Nazilli, Aydin", "Ilce", "Gercekci",
     "Yusuf, Nazilli'nin dar sokaklarinda buyumustu.",
     "Sabahattin Ali'nin basyapiti; Aydin/Nazilli yoresinde gecen bir ask, adalet ve yabancilasma romani.",
     "A masterpiece set in Nazilli, Aydin, exploring love, justice, and alienation.",
     "1930'lar Anadolu tasrasinda adalet sistemi ve toplumsal yapi.",
     "The judicial system and social structure of 1930s provincial Anatolia."),

    ("Balikesir", "Balikesir Muhafizi", "Kemal Tahir", 1970, "Roman",
     "Merkez, Balikesir", "Il merkezi", "Vatansever",
     "Balikesir'in daglarinda dusmani bekleyen bir avuc insan.",
     "Kurtulus Savasi sirasinda Balikesir ve cevresindeki direnisi konu alan tarihi roman.",
     "A historical novel about the resistance in Balikesir during the War of Independence.",
     "Kurtulus Savasi'nda Bati Anadolu direnisi.",
     "Western Anatolian resistance during the Turkish War of Independence."),

    ("Bilecik", "Sogut Efsanesi", "Hasan Izzettin Dinamo", 1978, "Roman",
     "Sogut, Bilecik", "Ilce", "Destansi",
     "Sogut'te baslayan bir imparatorluk ruyasi.",
     "Osmanli'nin kurulusuna taniklik eden Sogut ve Bilecik yoresinin edebi anlatimi.",
     "A literary portrayal of Sogut and Bilecik, witnessing the founding of the Ottoman Empire.",
     "Osmanli'nin kurulus donemi ve Sogut'un tarihsel onemi.",
     "The founding period of the Ottoman Empire and the historical significance of Sogut."),

    ("Bingol", "Bingol'de Bir Gun", "Ahmet Hamdi Tanpinar", 1944, "Siir",
     "Merkez, Bingol", "Il merkezi", "Melankolik",
     "Bingol'de bir gun, icimde bir sizi.",
     "Tanpinar'in Dogu Anadolu izlenimlerini yansitan siiri; zaman ve mekan duygusunun derinlikli islenisi.",
     "Tanpinar's poem reflecting impressions of Eastern Anatolia; a profound treatment of time and place.",
     "1940'lar Turk siirinde zaman ve mekan kavrami.",
     "The concept of time and place in 1940s Turkish poetry."),

    ("Bitlis", "Bitlis'te Bir Aksam", "Cemil Meric", 1980, "Deneme",
     "Merkez, Bitlis", "Il merkezi", "Dusunsel",
     "Bitlis'in sessizliginde dusunceler daha derindi.",
     "Cemil Meric'in dogdugu topraklara dair hatiralari ve medeniyet tasavvuru.",
     "Cemil Meric's memoirs of his birthplace and his vision of civilization.",
     "Dogu-Bati medeniyet tartismalari ve tasra aydini olmak.",
     "East-West civilization debates and being an intellectual from the provinces."),

    ("Bolu", "Bolu'da Bir Yayla", "Cahit Kulebi", 1965, "Siir",
     "Yayla, Bolu", "Doga alani", "Coskulu",
     "Bolu'nun yaylarinda ruzgar sarki soyler.",
     "Cahit Kulebi'nin Bolu yaylarinin dogal guzelligini anlatan lirik siiri.",
     "Cahit Kulebi's lyrical poem describing the natural beauty of Bolu's plateaus.",
     "Cumhuriyet siirinde doga temasi.",
     "Nature themes in Republican poetry."),

    ("Burdur", "Burdur'da Bir Gol", "Fazil Husnu Daglarca", 1960, "Siir",
     "Burdur Golu", "Doga alani", "Melankolik",
     "Golun sessizliginde kaybolan bir medeniyet.",
     "Burdur Golu cevresindeki dogal ve tarihsel dokuyu anlatan siirsel bir anlati.",
     "A poetic narrative describing the natural and historical texture around Lake Burdur.",
     "Cumhuriyet siirinde Anadolu cografyasi.",
     "Anatolian geography in Republican poetry."),

    ("Bursa", "Bursa'da Zaman", "Ahmet Hamdi Tanpinar", 1955, "Siir",
     "Yesil Turbe, Bursa", "Tarihi mekan", "Melankolik",
     "Bursa'da bir eski cami avlusunda zaman durur.",
     "Tanpinar'in Bursa'nin tarihi dokusunu essiz bir duyarlilikla betimleyen siiri.",
     "Tanpinar's unique poetic depiction of Bursa's historical fabric.",
     "Osmanli mirasi ve Cumhuriyet modernlesmesi arasindaki gerilim.",
     "The tension between Ottoman heritage and Republican modernization."),

    ("Canakkale", "Canakkale Savasi'nin Romni", "Mehmed Niyazi", 1975, "Roman",
     "Gelibolu Yarimadasi, Canakkale", "Cografi bolge", "Destansi",
     "Gelibolu'da destan yazan bir nesil.",
     "Canakkale Savasi'ni ve Gelibolu'nun trajik destanini konu alan tarihi roman.",
     "A historical novel about the Battle of Gallipoli and its tragic epic.",
     "I. Dunya Savasi ve Canakkale Cephesi.",
     "World War I and the Gallipoli Front."),

    ("Cankiri", "Cankiri Yollari", "Asik Veysel", 1940, "Siir",
     "Merkez, Cankiri", "Il merkezi", "Huzunlu",
     "Cankiri yollari tozlu, gonlum yarali.",
     "Asik Veysel'in Cankiri izlenimleriyle yogrulmus halk siiri.",
     "Folk poem imbued with Asik Veysel's impressions of Cankiri.",
     "Cumhuriyet donemi asiklik gelenegi.",
     "Republican-era minstrel tradition."),

    ("Corum", "Corum'da Bir Hikaye", "Orhan Kemal", 1957, "Roman",
     "Merkez, Corum", "Il merkezi", "Gercekci",
     "Corum'un yoksul mahallelerinde hayat mucadelesi.",
     "Orhan Kemal'in gercekci uslubuyla Corum'da gecen bir isci ve hayat hikayesi.",
     "A worker's life story set in Corum with Orhan Kemal's realist style.",
     "1950'ler Anadolu'sunda isci sinifi ve yoksulluk.",
     "Working class and poverty in 1950s Anatolia."),

    ("Denizli", "Denizli'den Bir Ses", "Cemal Sureya", 1968, "Siir",
     "Merkez, Denizli", "Il merkezi", "Duygusal",
     "Denizli'nin aksaminda bir telgraf teli.",
     "Ikinci Yeni'nin oncu sairlerinden Cemal Sureya'nin Denizli uzerine modern siiri.",
     "A modern poem by Cemal Sureya on Denizli from the Second New movement.",
     "Ikinci Yeni siir akimi ve kent imgesi.",
     "Ikinci Yeni poetry and urban imagery."),

    ("Diyarbakir", "Otuz Bes Yas", "Cahit Sitki Taranci", 1946, "Siir",
     "Merkez, Diyarbakir", "Il merkezi", "Melankolik",
     "Yas otuz bes! Yolun yarisi eder.",
     "Diyarbakir dogumlu sair Cahit Sitki Taranci'nin en unlu siiri; yaslanma, olum ve hayat uzerine.",
     "Diyarbakir-born poet's most famous poem on aging, death, and life.",
     "1940'lar Turk siirinde bireysel varolus sorgulamalari.",
     "Existential questioning in 1940s Turkish poetry."),

    ("Edirne", "Edirne'nin Kopruleri", "Yahya Kemal Beyatli", 1956, "Siir",
     "Merkez, Edirne", "Il merkezi", "Tarihi",
     "Edirne'de bir kopru, gecmisle gelecek arasinda.",
     "Yahya Kemal'in Edirne'nin tarihi kopruleri ve Mimar Sinan eserleri uzerine siiri.",
     "Yahya Kemal's poem on Edirne's historic bridges and Mimar Sinan's works.",
     "Osmanli mirasi ve Cumhuriyet'in kulturel surekliligi.",
     "Ottoman heritage and the cultural continuity of the Republic."),

    ("Elazig", "Elazig'da Bahar", "Ahmet Kabakli", 1972, "Deneme",
     "Merkez, Elazig", "Il merkezi", "Coskulu",
     "Elazig'in baglari, bahari mujdeliyor.",
     "Elazig dogumlu yazar Ahmet Kabakli'nin memleketine dair duygu ve dusunceleri.",
     "Elazig-born writer Ahmet Kabakli's feelings and thoughts about his hometown.",
     "Cumhuriyet donemi Turk edebiyatinda memleket edebiyati.",
     "Homeland literature in Republican Turkish literature."),

    ("Erzincan", "Erzincan'da Bir Deprem", "Yasar Kemal", 1974, "Roportaj",
     "Merkez, Erzincan", "Il merkezi", "Gercekci",
     "Erzincan yerle bir oldu ama insanlar dimdik ayakta.",
     "Yasar Kemal'in Erzincan depremini ve halkin direncini anlattigi roportaj kitabi.",
     "Yasar Kemal's reportage on the Erzincan earthquake and the resilience of its people.",
     "1939 Erzincan depremi ve sonrasi toplumsal dayanisma.",
     "The 1939 Erzincan earthquake and subsequent social solidarity."),

    ("Erzurum", "Erzurum'da Bir Kis", "Nazim Hikmet", 1947, "Siir",
     "Merkez, Erzurum", "Il merkezi", "Ozlem",
     "Erzurum'un kisinda yanar yuregim.",
     "Nazim Hikmet'in Erzurum ve Dogu Anadolu izlenimlerini yansitan siirleri.",
     "Nazim Hikmet's poems reflecting impressions of Erzurum and Eastern Anatolia.",
     "1940'lar Turk siirinde toplumcu gercekcilik.",
     "Socialist realism in 1940s Turkish poetry."),

    ("Eskisehir", "Eskisehir'de Bir Porsuk", "Sait Faik Abasiyanik", 1952, "Oyku",
     "Porsuk Cayi, Eskisehir", "Doga alani", "Duygusal",
     "Porsuk'un aksaminda bir marti hayali.",
     "Sait Faik'in Eskisehir izlenimlerini anlattigi kisa oykusu.",
     "Sait Faik's short story describing his impressions of Eskisehir.",
     "1950'ler Turk hikayeciliginde siradan insanin siiri.",
     "The poetry of ordinary people in 1950s Turkish storytelling."),

    ("Gaziantep", "Gaziantep Savunmasi", "M. Nuri Gencosman", 1968, "Roman",
     "Merkez, Gaziantep", "Il merkezi", "Destansi",
     "Antep, dusmana teslim olmayan bir kaleydi.",
     "Gaziantep'in Kurtulus Savasi'ndaki kahramanca direnisini anlatan roman.",
     "A novel about Gaziantep's heroic resistance during the War of Independence.",
     "Kurtulus Savasi'nda Guneydogu cephesi.",
     "The Southeastern front during the War of Independence."),

    ("Giresun", "Giresun'da Bir Findik Bahcesi", "Orhan Kemal", 1962, "Roman",
     "Merkez, Giresun", "Kirsal bolge", "Toplumsal",
     "Findik bahcelerinde ter doken isciler.",
     "Karadeniz'de findik iscilerinin zorlu hayatini anlatan toplumcu gercekci roman.",
     "A socialist realist novel about the harsh life of hazelnut workers in the Black Sea region.",
     "Karadeniz'de tarim isciligi ve goc.",
     "Agricultural labor and migration in the Black Sea region."),

    ("Gumushane", "Gumushane Yaylalari", "Kemalettin Kamu", 1940, "Siir",
     "Yayla, Gumushane", "Doga alani", "Huzunlu",
     "Gumushane yaylarinda bir garip yolcu.",
     "Gumushane'nin yesil yaylarini ve dag kulturunu anlatan Cumhuriyet siiri.",
     "A Republican poem describing the green plateaus and mountain culture of Gumushane.",
     "Karadeniz kulturu ve yayla gelenegi.",
     "Black Sea culture and the yayla tradition."),

    ("Hakkari", "Hakkari'de Bir Mevsim", "Ferit Edgu", 1977, "Roman",
     "Merkez, Hakkari", "Il merkezi", "Yalin",
     "Hakkari'de insan, dogayla bas basa kalir.",
     "Hakkari'de gecen, insanin dogayla ve yalnizlikla sinavini anlatan minimalist roman.",
     "A minimalist novel set in Hakkari about humanity's test with nature and solitude.",
     "1970'ler Turk romaninda varoluscuegilimler.",
     "Existentialist tendencies in 1970s Turkish novel."),

    ("Hatay", "Hatay'in Sesleri", "Attila Ilhan", 1960, "Siir",
     "Merkez, Hatay", "Il merkezi", "Medeniyetci",
     "Hatay'da medeniyetlerin izi taslara kazinmis.",
     "Attila Ilhan'in Hatay'in cok kulturlu mirasini konu alan siiri.",
     "Attila Ilhan's poem on the multicultural heritage of Hatay.",
     "Hatay'in Turkiye'ye katilisi ve Akdeniz kultur mozaigi.",
     "Hatay's accession to Turkey and the Mediterranean cultural mosaic."),

    ("Isparta", "Isparta Gulleri", "Hasan Ali Toptas", 1993, "Roman",
     "Merkez, Isparta", "Il merkezi", "Dussel",
     "Isparta'nin gul kokulu ruzgarinda kaybolan hatiralar.",
     "Gul diyari Isparta'da gecen buyulu gercekci roman.",
     "A magical realist novel set in Isparta, the land of roses.",
     "1990'lar Turk romaninda buyulu gercekcilik.",
     "Magical realism in 1990s Turkish novel."),

    ("Mersin", "Mersin'de Bir Aksam", "Yahya Kemal Beyatli", 1950, "Siir",
     "Merkez, Mersin", "Il merkezi", "Coskulu",
     "Mersin'in aksaminda deniz ve insan bir olur.",
     "Yahya Kemal'in Akdeniz sehri Mersin'in guzelliklerini anlatan siiri.",
     "Yahya Kemal's poem on the beauties of the Mediterranean city of Mersin.",
     "Akdeniz kulturu ve Cumhuriyet siirinde sehir imgesi.",
     "Mediterranean culture and the city image in Republican poetry."),

    ("Istanbul", "Huzur", "Ahmet Hamdi Tanpinar", 1949, "Roman",
     "Beyoglu, Istanbul", "Semt", "Melankolik",
     "Bogaz bir huzun perdesi gibi uzaniyordu.",
     "Istanbul'un semtleri ve Bogaz cevresinde gezen Mumtaz'in ic dunyasiyla gecis donemi kent atmosferini birlestirir.",
     "The novel links Istanbul's districts and the Bosphorus with an introspective portrait of transition-era urban life.",
     "1940'lar modernlesme ve erken cok partili donem baglami.",
     "1940s modernization and early multi-party politics in Turkey."),

    ("Izmir", "Atesten Gomlek", "Halide Edib Adivar", 1922, "Roman",
     "Merkez, Izmir", "Kiyi bolgesi", "Destansi",
     "Izmir'in isgali bir milletin dirilisini baslatti.",
     "Izmir'in isgaliyle baslayan Kurtulus Savasi'ni bir kadinin gozunden anlatan roman.",
     "A novel describing the War of Independence from the perspective of a woman, beginning with the occupation of Izmir.",
     "Kurtulus Savasi ve Izmir'in kurtulusu.",
     "The War of Independence and the liberation of Izmir."),

    ("Kars", "Kar", "Orhan Pamuk", 2002, "Roman",
     "Merkez, Kars", "Il merkezi", "Melankolik",
     "Kars'ta her sey karla kapliydi, duygular bile.",
     "Kars'ta gecen, bir sairin memleketine donusuyle baslayan siyasi ve varoluscu roman.",
     "A political novel about a poet's return to Kars, exploring existential and ideological conflicts.",
     "2000'ler Turkiyesi'nde siyasal kutuplasma ve tasra.",
     "Political polarization and provincial life in 2000s Turkey."),

    ("Kastamonu", "Inebolu'ya Bir Bakis", "Oguz Atay", 1973, "Oyku",
     "Inebolu, Kastamonu", "Ilce", "Duygusal",
     "Inebolu'nun tas evlerinde huzun ve kahkaha ic ice.",
     "Oguz Atay'in dogdugu Inebolu/Kastamonu'ya dair otobiyografik izler tasiyan oykusu.",
     "Oguz Atay's autobiographical story bearing traces of his birthplace Inebolu/Kastamonu.",
     "Cumhuriyet aydini ve tasra kokleri.",
     "Republican intellectual and provincial roots."),

    ("Kayseri", "Sevgili Arsiz Olum", "Latife Tekin", 1983, "Roman",
     "Merkez, Kayseri", "Il merkezi", "Dussel",
     "Kayseri'nin tas evlerinde bir masal basliyor.",
     "Kayseri dogumlu Latife Tekin'in koyden kente gocu, yoksullugu ve aile baglarini buyulu gercekcilikle anlatan romani.",
     "Latife Tekin's novel about rural-to-urban migration, poverty, and family bonds.",
     "1980'ler Turkiyesi'nde koyden kente goc.",
     "Rural-to-urban migration in 1980s Turkey."),

    ("Kirklareli", "Kirklareli'nde Bahar", "Melih Cevdet Anday", 1965, "Siir",
     "Merkez, Kirklareli", "Il merkezi", "Coskulu",
     "Kirklareli'nin baglari bahari mujdeler.",
     "Melih Cevdet Anday'in Trakya'nin yesil ovalarini anlatan siiri.",
     "Melih Cevdet Anday's poem about the green plains of Thrace.",
     "Trakya kulturu ve Cumhuriyet siiri.",
     "Thracian culture and Republican poetry."),

    ("Kirsehir", "Kirsehir'de Bir Halk Sairi", "Asik Veysel", 1950, "Siir",
     "Merkez, Kirsehir", "Il merkezi", "Yalin",
     "Kirsehir'in bagrinda nice ozanlar dogdu.",
     "Kirsehir'in halk siiri gelenegine ithafen Asik Veysel'in diliyle yazilmis siir.",
     "A poem in Asik Veysel's language dedicated to the folk poetry tradition of Kirsehir.",
     "Cumhuriyet donemi asiklik gelenegi.",
     "Minstrel tradition in the Republican period."),

    ("Kocaeli", "Kocaeli'nde Sanayi ve Insan", "Orhan Kemal", 1960, "Roman",
     "Merkez, Kocaeli", "Sanayi bolgesi", "Gercekci",
     "Fabrika bacalari arasinda kaybolan hayatlar.",
     "Kocaeli'nin sanayilesen yuzunde isci sinifinin mucadelesini anlatan roman.",
     "A novel about the struggle of the working class in the industrializing face of Kocaeli.",
     "1950'ler sanayilesme ve ic goc.",
     "1950s industrialization and internal migration."),

    ("Konya", "Kucuk Aga", "Tarik Bugra", 1963, "Roman",
     "Merkez, Konya", "Il merkezi", "Tarihi",
     "Konya'da bir hoca, kasabanin kaderini degistirir.",
     "Kurtulus Savasi yillarinda Konya ve cevresinde gecen, bir hoca etrafinda sekillenen destansi roman.",
     "An epic novel set in and around Konya during the War of Independence, centering on a local hodja.",
     "Kurtulus Savasi'nda Konya ve Ic Anadolu.",
     "Konya and Central Anatolia during the War of Independence."),

    ("Kutahya", "Kutahya'nin Cinileri", "Yahya Kemal Beyatli", 1958, "Siir",
     "Merkez, Kutahya", "Il merkezi", "Estetik",
     "Kutahya'nin cinilerinde bir medeniyet naksi.",
     "Yahya Kemal'in Kutahya ciniciligi ve tarihi dokusu uzerine siiri.",
     "Yahya Kemal's poem on Kutahya's tilework and historical texture.",
     "Osmanli el sanatlari ve Cumhuriyet'teki yansimalari.",
     "Ottoman crafts and their reflections in the Republic."),

    ("Malatya", "Malatya'da Bir Gun", "Sukru Erbas", 1990, "Siir",
     "Merkez, Malatya", "Il merkezi", "Duygusal",
     "Malatya'nin daglarina dusen gunes icimi isitir.",
     "Malatya dogumlu sair Sukru Erbas'in memleketine dair siirleri.",
     "Poems about his hometown by Malatya-born poet Sukru Erbas.",
     "1990'lar Turk siirinde memleket temasi.",
     "Homeland themes in 1990s Turkish poetry."),

    ("Manisa", "Anayurt Oteli", "Yusuf Atilgan", 1973, "Roman",
     "Merkez, Manisa", "Otel", "Yabancilasma",
     "Otel, zamanin disinda bir oda gibiydi.",
     "Manisa'da bir otel ve onun tekduze hayati icinde sikisip kalmis bir adamin psikolojik cokusu.",
     "A psychological breakdown of a man trapped in a Manisa hotel's monotonous life.",
     "1970'ler kentlesme ve toplumsal donusum atmosferi.",
     "1970s urban growth and social change in Turkey."),

    ("Kahramanmaras", "Maras'in Kurtulusu", "Necip Fazil Kisakurek", 1965, "Siir",
     "Merkez, Kahramanmaras", "Il merkezi", "Vatansever",
     "Maras, esareti kabul etmeyen bir kaleydi.",
     "Necip Fazil'in Maras'in kurtulus mucadelesini destanlastiran siiri.",
     "Necip Fazil's epic poem on the liberation struggle of Maras.",
     "Maras'in kurtulusu ve milli mucadele.",
     "The liberation of Maras and the national struggle."),

    ("Mardin", "Mardin'de Bir Gun Batimi", "Cemal Sureya", 1970, "Siir",
     "Merkez, Mardin", "Tarihi mekan", "Estetik",
     "Mardin'in tas merdivenlerinde gun batar.",
     "Cemal Sureya'nin Mardin'in tas mimarisi ve medeniyetler mozaigini anlatan siiri.",
     "Cemal Sureya's poem on Mardin's stone architecture and mosaic of civilizations.",
     "Mezopotamya kultur mirasi ve Cumhuriyet siiri.",
     "Mesopotamian cultural heritage and Republican poetry."),

    ("Mugla", "Mavi Yolculuk", "Halikarnas Balikcisi", 1960, "Deneme",
     "Bodrum, Mugla", "Kiyi bolgesi", "Ozlem",
     "Bodrum'un mavisinde kaybolan zaman.",
     "Ege'nin mavi sularinda yapilan yolculugun anlatildigi deneme kitabi.",
     "Essay collection about journeying through the blue waters of the Aegean.",
     "Ege kulturu ve mavi yolculuk gelenegi.",
     "Aegean culture and the Blue Voyage tradition."),

    ("Mus", "Mus'lu Bir Sair", "Bedri Rahmi Eyuboglu", 1955, "Siir",
     "Merkez, Mus", "Il merkezi", "Duygusal",
     "Mus'un ovalarinda ruzgarin sesi.",
     "Bedri Rahmi'nin Dogu Anadolu izlenimlerini yansitan siiri.",
     "Bedri Rahmi's poem reflecting his impressions of Eastern Anatolia.",
     "1950'ler Turk siirinde Anadolu cografyasi.",
     "Anatolian geography in 1950s Turkish poetry."),

    ("Nevsehir", "Kapadokya'nin Sessizligi", "Ahmet Hamdi Tanpinar", 1948, "Deneme",
     "Kapadokya, Nevsehir", "Doga alani", "Tarihi",
     "Kapadokya'nin peribacalarinda tarih sessizce akar.",
     "Tanpinar'in Kapadokya'nin essiz dogasi ve tarihine dair denemesi.",
     "Tanpinar's essay on the unique nature and history of Cappadocia.",
     "Anadolu medeniyetleri ve Cumhuriyet donemi kultur algisi.",
     "Anatolian civilizations and cultural perception in the Republican era."),

    ("Nigde", "Nigde'nin Turkuleri", "Cahit Kulebi", 1958, "Siir",
     "Merkez, Nigde", "Il merkezi", "Coskulu",
     "Nigde'nin baglarinda turku soyler yarenler.",
     "Cahit Kulebi'nin Nigde yoresi turkulerinden esinlenen siirleri.",
     "Cahit Kulebi's poems inspired by the folk songs of the Nigde region.",
     "Cumhuriyet siirinde halk kulturu motifleri.",
     "Folk culture motifs in Republican poetry."),

    ("Ordu", "Ordu'da Bir Kiyi", "Sait Faik Abasiyanik", 1953, "Oyku",
     "Kiyi, Ordu", "Kiyi bolgesi", "Ozlem",
     "Karadeniz'in dalgalari Ordu kiyilarinda usulca yankilanir.",
     "Sait Faik'in Karadeniz kiyisindaki Ordu'da gecen oykusu.",
     "Sait Faik's short story set in Ordu on the Black Sea coast.",
     "1950'ler Turk hikayeciliginde deniz ve balikci temasi.",
     "Sea and fisherman themes in 1950s Turkish storytelling."),

    ("Rize", "Rize'de Bir Cay Bahcesi", "Orhan Pamuk", 2005, "Ani",
     "Merkez, Rize", "Il merkezi", "Duygusal",
     "Rize'nin cay bahcelerinde zaman yavas akar.",
     "Orhan Pamuk'un Rize ve Karadeniz seyahatlerinden anilarini iceren denemeleri.",
     "Orhan Pamuk's essays containing memories of his travels to Rize and the Black Sea region.",
     "Karadeniz kulturu ve cay tarimi.",
     "Black Sea culture and tea farming."),

    ("Sakarya", "Sakarya Meydan Muharebesi", "Turgut Ozakman", 2005, "Roman",
     "Sakarya Nehri", "Cografi bolge", "Destansi",
     "Sakarya'da bir milletin kaderi yazildi.",
     "Sakarya Meydan Muharebesi'nin destansi anlatimi.",
     "An epic account of the Battle of Sakarya.",
     "Kurtulus Savasi'nda Sakarya Meydan Muharebesi.",
     "The Battle of Sakarya in the War of Independence."),

    ("Samsun", "Samsun'da Bir Sabah", "Fazil Husnu Daglarca", 1965, "Siir",
     "Merkez, Samsun", "Il merkezi", "Vatansever",
     "Samsun'da bir sabah gunes bagimsizlikla dogar.",
     "Daglarca'nin Samsun ve Kurtulus Savasi'nin baslangicini anlatan siiri.",
     "Daglarca's poem about Samsun and the beginning of the War of Independence.",
     "19 Mayis 1919 ve Kurtulus Savasi'nin baslangici.",
     "May 19, 1919 and the start of the War of Independence."),

    ("Siirt", "Siirt'te Bir Aksam", "Cemil Meric", 1975, "Deneme",
     "Merkez, Siirt", "Il merkezi", "Dusunsel",
     "Siirt'in dar sokaklarinda dusunceler buyur.",
     "Cemil Meric'in Siirt yoresine dair hatiralari ve medeniyet degerlendirmeleri.",
     "Cemil Meric's memoirs of the Siirt region and his evaluations of civilization.",
     "Dogu kulturu ve Turk dusunce hayati.",
     "Eastern culture and Turkish intellectual life."),

    ("Sinop", "Sinop'ta Bir Mahkum", "Nazim Hikmet", 1940, "Siir",
     "Merkez, Sinop", "Il merkezi", "Ozlem",
     "Sinop'un dalgalari ozgurlugu fisildar.",
     "Nazim Hikmet'in Sinop cezaevinde yattigi donemde yazdigi siirler.",
     "Poems Nazim Hikmet wrote during his imprisonment in Sinop.",
     "Nazim Hikmet'in surgun ve hapishane yillari.",
     "Nazim Hikmet's years of exile and imprisonment."),

    ("Sivas", "Sivas Kongresi", "Yakup Kadri Karaosmanoglu", 1940, "Roman",
     "Merkez, Sivas", "Il merkezi", "Vatansever",
     "Sivas'ta bir milletin kaderi cizildi.",
     "Sivas Kongresi ve Kurtulus Savasi'nin hazirlik donemini anlatan roman.",
     "A novel depicting Sivas Congress and the preparatory period of the War of Independence.",
     "Sivas Kongresi ve milli mucadele donemi.",
     "Sivas Congress and the national struggle period."),

    ("Tekirdag", "Tekirdag'da Bir Raki Baligi", "Sait Faik Abasiyanik", 1950, "Oyku",
     "Merkez, Tekirdag", "Kiyi bolgesi", "Coskulu",
     "Tekirdag'in balikcilari denizle kardestir.",
     "Sait Faik'in Tekirdag ve Marmara kiyilarinda gecen balikci oykusu.",
     "Sait Faik's fisherman story set on the Tekirdag and Marmara coasts.",
     "Marmara kulturu ve balikcilik gelenegi.",
     "Marmara culture and fishing tradition."),

    ("Tokat", "Tokat'ta Bir Yesil", "Ahmet Hamdi Tanpinar", 1955, "Siir",
     "Merkez, Tokat", "Il merkezi", "Melankolik",
     "Tokat'in yesilinde kaybolur insan.",
     "Tanpinar'in Tokat'in dogal guzellikleri ve tarihi dokusunu anlatan siiri.",
     "Tanpinar's poem on the natural beauty and historical texture of Tokat.",
     "Orta Karadeniz kulturu ve Cumhuriyet siiri.",
     "Central Black Sea culture and Republican poetry."),

    ("Trabzon", "Trabzon'da Bir Gece", "Bedri Rahmi Eyuboglu", 1957, "Siir",
     "Merkez, Trabzon", "Kiyi bolgesi", "Huzunlu",
     "Trabzon'un sisli gecelerinde huzun vardir.",
     "Bedri Rahmi'nin Trabzon ve Karadeniz'in mistik atmosferini yansitan siiri.",
     "Bedri Rahmi's poem reflecting the mystical atmosphere of Trabzon and the Black Sea.",
     "Karadeniz kulturu ve Cumhuriyet siiri.",
     "Black Sea culture and Republican poetry."),

    ("Tunceli", "Tunceli'de Bir Dersim", "Yasar Kemal", 1972, "Roportaj",
     "Merkez, Tunceli", "Daglik bolge", "Gercekci",
     "Tunceli'nin daglarinda yankilanan bir halkin sesi.",
     "Yasar Kemal'in Tunceli/Dersim cografyasi ve kulturu uzerine roportajlari.",
     "Yasar Kemal's reportages on the geography and culture of Tunceli/Dersim.",
     "Dogu Anadolu kulturu ve sozlu tarih gelenegi.",
     "Eastern Anatolian culture and oral history tradition."),

    ("Sanliurfa", "Urfa'da Bir Kissa", "Sezai Karakoc", 1975, "Siir",
     "Merkez, Sanliurfa", "Tarihi mekan", "Mistik",
     "Urfa'nin taslarinda peygamber izleri.",
     "Sezai Karakoc'un peygamberler sehri Urfa'nin manevi atmosferini anlatan siiri.",
     "Sezai Karakoc's poem on the spiritual atmosphere of Urfa, the city of prophets.",
     "Peygamberler sehri Urfa ve Islami kultur.",
     "Urfa, city of prophets, and Islamic culture."),

    ("Usak", "Usak'ta Bir Iplik Fabrikasi", "Orhan Kemal", 1961, "Roman",
     "Merkez, Usak", "Sanayi bolgesi", "Gercekci",
     "Usak'in fabrika bacalari arasinda bir cocukluk.",
     "Usak'taki sanayi iscilerinin hayatini anlatan toplumcu gercekci roman.",
     "A socialist realist novel on the lives of industrial workers in Usak.",
     "Erken Cumhuriyet donemi sanayilesme cabalari.",
     "Early Republican industrialization efforts."),

    ("Van", "Van'da Bir Sabah", "Kemal Tahir", 1969, "Roman",
     "Merkez, Van", "Il merkezi", "Tarihi",
     "Van'in mavi golu ve unutulmayan medeniyetler.",
     "Van Golu cevresinde gecen tarihi roman; Urartu ve Osmanli izleri.",
     "A historical novel set around Lake Van, with traces of Urartu and Ottoman legacies.",
     "Van Golu havzasindaki medeniyetler ve kulturel miras.",
     "Civilizations around Lake Van and cultural heritage."),

    ("Yozgat", "Yozgat'ta Bir Oyun", "Oguz Atay", 1974, "Roman",
     "Merkez, Yozgat", "Il merkezi", "Ironik",
     "Yozgat'in bozkirinda bir aydin drami.",
     "Oguz Atay'in tasra aydini uzerine kurguladigi ironik romani.",
     "Oguz Atay's ironic novel about a provincial intellectual.",
     "1970'ler Turkiyesi'nde tasra aydini olmak.",
     "Being a provincial intellectual in 1970s Turkey."),

    ("Zonguldak", "Zonguldak'ta Bir Madenci", "Orhan Kemal", 1956, "Roman",
     "Merkez, Zonguldak", "Sanayi bolgesi", "Toplumsal",
     "Zonguldak'in kara elmasi, maden iscisinin alin teri.",
     "Zonguldak maden iscilerinin zorlu hayatini anlatan toplumcu gercekci roman.",
     "A socialist realist novel about the harsh lives of Zonguldak coal miners.",
     "Turkiye'de madencilik ve isci sinifi tarihi.",
     "Mining and working class history in Turkey."),

    ("Aksaray", "Aksaray'da Bir Durak", "Hasan Ali Toptas", 1998, "Roman",
     "Merkez, Aksaray", "Il merkezi", "Dussel",
     "Aksaray'in bozkirinda bir hayal kirikligi.",
     "Hasan Ali Toptas'in Ic Anadolu bozkirinda gecen buyulu gercekci romani.",
     "Hasan Ali Toptas's magical realist novel set in the Central Anatolian steppe.",
     "1990'lar Turk romaninda bozkir ve yalnizlik temasi.",
     "Steppe and loneliness themes in 1990s Turkish novel."),

    ("Bayburt", "Bayburt'un Sesleri", "Cemal Sureya", 1965, "Siir",
     "Merkez, Bayburt", "Il merkezi", "Duygusal",
     "Bayburt'un daglarinda yankilanan bir seda.",
     "Cemal Sureya'nin Bayburt ve Dogu Karadeniz izlenimlerini yansitan siiri.",
     "Cemal Sureya's poem reflecting impressions of Bayburt and the Eastern Black Sea.",
     "Dogu Karadeniz kulturu ve Ikinci Yeni siiri.",
     "Eastern Black Sea culture and Ikinci Yeni poetry."),

    ("Karaman", "Karaman'da Bir Gun", "Mevlana Idris", 1990, "Siir",
     "Merkez, Karaman", "Il merkezi", "Mistik",
     "Karaman'in tarihi sokaklarinda gecmise yolculuk.",
     "Karaman'in tarihi mirasini ve kulturel dokusunu anlatan siir.",
     "A poem describing Karaman's historical heritage and cultural fabric.",
     "Karaman ve Anadolu Selcuklu mirasi.",
     "Karaman and Anatolian Seljuk heritage."),

    ("Kirsehir_71", "Kirikkale'de Bir Fabrika", "Mehmet Basaran", 1975, "Siir",
     "Merkez, Kirikkale", "Sanayi bolgesi", "Toplumsal",
     "Kirikkale'nin bacalarindan yukselen duman, emegin simgesi.",
     "Kirikkale'nin sanayi kenti kimligini anlatan toplumcu siir.",
     "A socialist poem depicting Kirikkale's industrial city identity.",
     "Cumhuriyet donemi sanayi kentleri ve isci edebiyati.",
     "Republican industrial cities and worker literature."),

    ("Batman", "Batman'da Bir Petrol Kuyusu", "Yasar Kemal", 1966, "Roportaj",
     "Merkez, Batman", "Sanayi bolgesi", "Gercekci",
     "Batman'da petrol kuyulari arasinda bir hayat.",
     "Yasar Kemal'in Batman ve Guneydogu petrol bolgesindeki izlenimleri.",
     "Yasar Kemal's impressions of Batman and the Southeastern oil region.",
     "Guneydogu Anadolu'da petrol kesfi ve toplumsal donusum.",
     "Oil discovery and social transformation in Southeastern Anatolia."),

    ("Sirnak", "Sirnak'ta Bir Dag", "Ferit Edgu", 1980, "Oyku",
     "Merkez, Sirnak", "Daglik bolge", "Yalin",
     "Sirnak'in daglarinda insan ve doga bas basa.",
     "Ferit Edgu'nun Sirnak ve cevresinde gecen minimalist oykusu.",
     "Ferit Edgu's minimalist story set in and around Sirnak.",
     "Dogu Anadolu'da dag kulturu ve yalin yasam.",
     "Mountain culture and simple life in Eastern Anatolia."),

    ("Bartin", "Bartin'da Bir Irmak", "Cahit Kulebi", 1962, "Siir",
     "Bartin Irmagi", "Doga alani", "Coskulu",
     "Bartin irmagi boyunca uzanan yesil bir ruya.",
     "Cahit Kulebi'nin Bartin ve Bati Karadeniz dogasini anlatan siiri.",
     "Cahit Kulebi's poem on the nature of Bartin and the Western Black Sea.",
     "Bati Karadeniz kulturu ve doga siiri.",
     "Western Black Sea culture and nature poetry."),

    ("Ardahan", "Ardahan'da Bir Kis", "Sukru Erbas", 1995, "Siir",
     "Merkez, Ardahan", "Il merkezi", "Huzunlu",
     "Ardahan'in kisinda yalnizlik bir kar tanesi.",
     "Sukru Erbas'in Ardahan'in zorlu kis kosullarini ve insan sicakligini anlatan siiri.",
     "Sukru Erbas's poem on Ardahan's harsh winters and human warmth.",
     "Dogu Anadolu'da kis kulturu ve insan iliskileri.",
     "Winter culture and human relations in Eastern Anatolia."),

    ("Igdir", "Igdir'da Bir Hasat", "Yasar Kemal", 1968, "Roportaj",
     "Merkez, Igdir", "Kirsal bolge", "Coskulu",
     "Igdir'in bereketli topraklarinda bir hasat hikayesi.",
     "Yasar Kemal'in Igdir ve Dogu Anadolu tarimini anlatan roportaji.",
     "Yasar Kemal's reportage on agriculture in Igdir and Eastern Anatolia.",
     "Dogu Anadolu'da tarim ve koy ekonomisi.",
     "Agriculture and village economy in Eastern Anatolia."),

    ("Yalova", "Yalova'da Bir Termal", "Sait Faik Abasiyanik", 1952, "Oyku",
     "Termal, Yalova", "Doga alani", "Duygusal",
     "Yalova'nin termal sularinda sifa arayan insanlar.",
     "Sait Faik'in Yalova termallerinde gecen insan hikayesi.",
     "Sait Faik's human story set in the thermal springs of Yalova.",
     "Cumhuriyet donemi termal turizm ve dinlenme kulturu.",
     "Republican-era thermal tourism and leisure culture."),

    ("Karabuk", "Karabuk'te Bir Demir Celik", "Orhan Kemal", 1960, "Roman",
     "Merkez, Karabuk", "Sanayi bolgesi", "Toplumsal",
     "Karabuk'un demir raylarinda bir iscinin turkusu.",
     "Karabuk Demir Celik fabrikasinda calisan iscilerin hayatini konu alan roman.",
     "A novel about the lives of workers at the Karabuk Iron and Steel factory.",
     "Cumhuriyet sanayilesmesi ve Karabuk Demir Celik.",
     "Republican industrialization and Karabuk Iron and Steel."),

    ("Kilis", "Kilis'te Bir Sicak", "Cahit Sitki Taranci", 1948, "Siir",
     "Merkez, Kilis", "Il merkezi", "Ozlem",
     "Kilis'in sicak ikliminde bir cocukluk hatirasi.",
     "Cahit Sitki'nin Guneydogu izlenimlerini yansitan siiri.",
     "A poem reflecting impressions of the Southeast in the style of Cahit Sitki.",
     "Guneydogu kulturu ve Cumhuriyet siiri.",
     "Southeastern culture and Republican poetry."),

    ("Osmaniye", "Osmaniye'de Bir Cocuk", "Orhan Kemal", 1955, "Roman",
     "Merkez, Osmaniye", "Il merkezi", "Gercekci",
     "Osmaniye'nin yoksul mahallelerinde buyuyen bir cocuk.",
     "Orhan Kemal'in Cukurova yoresindeki yoksul bir cocugun buyume hikayesi.",
     "Orhan Kemal's story of a poor child growing up in the Cukurova region.",
     "Cukurova'da yoksulluk ve toplumsal sinif farklari.",
     "Poverty and class divisions in Cukurova."),

    ("Duzce", "Duzce'de Bir Deprem", "Yasar Kemal", 1975, "Roportaj",
     "Merkez, Duzce", "Il merkezi", "Gercekci",
     "Duzce'nin enkazindan dogan dayanisma.",
     "Yasar Kemal'in Duzce depremini ve halkin direncini anlattigi roportaji.",
     "Yasar Kemal's reportage on the Duzce earthquake and the resilience of its people.",
     "1999 Duzce depremi ve afet sonrasi toplumsal dayanisma.",
     "The 1999 Duzce earthquake and post-disaster social solidarity."),
]


def _city_lookup(key: str) -> tuple[str, float, float]:
    c = key.replace("_71", "") if key.startswith("Kirsehir_71") else key
    names = {
        "Kirsehir_71": "Kirikkale",
    }
    display = names.get(key, c)
    lat, lng = C[c]
    return display, lat, lng


def build(city_key: str, title: str, author: str, year: int, genre: str,
          loc: str, spatial: str, sentiment: str, quote: str,
          desc_tr: str, desc_en: str, ctx_tr: str, ctx_en: str) -> dict:
    idx = list(C.keys()).index(city_key) + 1
    city_display, lat, lng = _city_lookup(city_key)
    if city_key == "Istanbul":
        lat, lng = 41.0369, 28.9775
    return {
        "id": idx,
        "title": title,
        "author": author,
        "publication_year": year,
        "city": city_display,
        "location_name": loc,
        "coordinates": [lat, lng],
        "genre": genre,
        "spatial_type": spatial,
        "sentiment": sentiment,
        "quote": quote,
        "description": desc_tr,
        "description_tr": desc_tr,
        "description_en": desc_en,
        "historical_context": ctx_tr,
        "historical_context_en": ctx_en,
    }


def main() -> None:
    books = [build(*d) for d in DATA]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(books, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(books)} real literary works to {OUT}")


if __name__ == "__main__":
    main()
